# Generated by Django 4.1.7 on 2023-03-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('country_idx', models.IntegerField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=10)),
                ('country_dcode', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('Male', '남성'), ('Female', '여성')], max_length=6)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('nationality', models.ForeignKey(db_column='nationality', default=191, on_delete=django.db.models.deletion.CASCADE, related_name='user_nationality', to='users.nationality')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
